<?php
session_start();
if($_SESSION["lp"]=="0") header('Location: start.php');
echo "<html>";
echo "<head>";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"/>\n";
echo "</head>";
echo "<body>";
echo "<h1>M.S.RAMAIAH INSTITUTE OF TECHNOLOGY</h1>";
echo "<hr>";
echo "<br/>";
echo "<h2>EDIT</h2><br/>";
echo "<div>";
echo "<form action=\"adminreset.php\">";
echo "<input type=\"SUBMIT\" value=\"CLEAR THE ALLOTMENT OF ELECTIVES\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "<form action=\"studentreset.php\">";
echo "<input type=\"SUBMIT\" value=\"CLEAR ALL STUDENTS SELECTION\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "<form action=\"teacher.php\">";
echo "<input type=\"SUBMIT\" value=\"ALLOT TEACHERS\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "<form action=\"class_param.php\">";
echo "<input type=\"SUBMIT\" value=\"CHANGE CLASS PARAMETERS\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "<form action=\"admin_menu.php\">";
echo "<input type=\"submit\" value=\"BACK TO MENU\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "</body>";
echo "</html>";
?>