<?php
session_start();
if($_SESSION["lp"]=="0") header('Location: start.php');
$_SESSION["error"]=0;
$_SESSION["success"]=1;
echo "<html>";
echo "<head>";
echo "<link rel=\"stylesheet\" type=\"text/css\"";
echo "href=\"style.css\"/>\n";
echo "</head>";
echo "<body>";
echo "<h1>M.S.RAMAIAH INSTITUTE OF TECHNOLOGY</h1>";
echo "<hr>";
echo "<br/>";
echo "<h2>COORDINATOR MENU</h2><br/>";
echo "<div>";
echo "<form action=\"edit.php\">";
echo "<input type=\"SUBMIT\" value=\"EDIT\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "<form action=\"student_selection.php\">";
echo "<input type=\"SUBMIT\" value=\"SEE THE CURRENT STUDENT SELECTION\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "<form action=\"admin_allot.php\">";
echo "<input type=\"SUBMIT\" value=\"ALLOT ELECTIVES\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "<form action=\"student_info.php\">";
echo "<input type=\"submit\" value=\"FINAL ALLOTED\">";
echo "</input>";
echo "</form>";
echo "<br>";
echo "<form action=\"l.php\">";
echo "<input type=\"submit\" value=\"LOGOUT\">";
echo "</input>";
echo "<br>";
echo "</form>";
echo "</body>";
echo "</html>";
?>